# 예시: 마스터 주소나 기본 설정
spark.master                      local[*]
spark.driver.memory               2g
spark.executor.memory             2g
# MySQL 커넥터 패키지 등 공통 추가
spark.jars.packages               com.mysql:mysql-connector-j:8.3.0